- Microsoft.FeatureManagement.sln
- README.md
- examples/ConsoleApp/AccountServiceContext.cs
- examples/ConsoleApp/ConsoleApp.csproj
- examples/ConsoleApp/FeatureFilters/AccountIdFilter.cs
- examples/ConsoleApp/FeatureFilters/IAccountContext.cs
- examples/ConsoleApp/Program.cs
- examples/ConsoleApp/appsettings.json
- src/Microsoft.FeatureManagement/ContextualFeatureFilterEvaluator.cs
- src/Microsoft.FeatureManagement/FeatureManagementBuilder.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/FeatureManagerSnapshot.cs
- src/Microsoft.FeatureManagement/IContextualFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureFilterMetadata.cs
- src/Microsoft.FeatureManagement/IFeatureManagementBuilder.cs
- src/Microsoft.FeatureManagement/IFeatureManager.cs
- tests/Tests.FeatureManagement/AppContext.cs
- tests/Tests.FeatureManagement/ContextualTestFilter.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/IAccountContext.cs
- tests/Tests.FeatureManagement/InvalidFeatureFilter.cs
- tests/Tests.FeatureManagement/TestFilter.cs
- tests/Tests.FeatureManagement/appsettings.json
This PR introduces the capability for applications to pass in a custom context to the feature management system for use in evaluating the state of features. The existing design for this PR is to gather this information from ambient contexts available within the application such as `HttpContext`. The problem with this existing design is that it is not available in console applications and many other frameworks.
The ability to pass a context when evaluating a feature has been added to `IFeatureManager`.
```
IFeatureManager fm = services.GetRequiredService<IFeatureManager>();
fm.IsEnabled("featureName", new MyApplicationContext
{
UserId = "someUser"
});
```
Contextual feature filters are feature filters that can utilize a context provided by the application when evaluating whether a feature …
> Added the capability to pass in a context when checking if a feature is enabled.

- examples/FeatureFlagDemo/FeatureFlagDemo.csproj
- examples/FeatureFlagDemo/Program.cs
- examples/FeatureFlagDemo/Startup.cs
- src/Microsoft.FeatureManagement/ConfigurationFeatureSettingsProvider.cs
A perf analysis of the library pointed out a bottle neck in the feature management pipeline during obtaining feature settings. This is due to the fact that sections in the .NET Core configuration were being enumerated on every lookup.
The `ConfigurationFeatureSettingsProvider` has been improved to cache feature settings when they have been read from the .NET Core configuration system. The `IConfiguration`'s reload token is used to track when the configuration has become stale.
`ConfigurationFeatureSettingsProvider` now implements `IDisposable` since it registers a callback on a reload token. The disposable of this will happen when the service container is disposed.
> Added feature settings caching.

- examples/ConsoleApp/Program.cs
The console application example for feature management did not dispose the `ServiceProvider` returned from `services.BuildServiceProvider()`. This PR fixes the issue.
> Update console application example to properly dispose service provider.

- src/Microsoft.FeatureManagement/FeatureManagementError.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
Currently, the feature manager throws an `InvalidOperationException` in the event that multiple feature filters match a name provided in the feature's filter list. The InvalidOperationException constitutes an error that doesn't really make sense for this type of problem. 
Now that we have the `FeatureManagementException` we can propogate the correct error, `AmbigousFeatureFilter`.
> Updated feature manager to throw FeatureManagementException instead of InvalidOperationException.

- README.md
It's not immediately visible from GitHub's diff view, but the second change is a correction of `FireFox` to `Firefox`.
> Minor corrections to docs

- examples/ConsoleApp/ConsoleApp.csproj
- examples/FeatureFlagDemo/FeatureFlagDemo.csproj
- examples/FeatureFlagDemo/Startup.cs
- examples/TargetingConsoleApp/TargetingConsoleApp.csproj
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
With the release of .NET Core 3.0, many ASP.NET Core assemblies are no longer published to NuGet as packages. ([info](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio))
So using libraries that target only `netstandard2.0` will lead to conflicts in `netcoreapp3.1` when you are getting old versions of packages as transient dependencies and you are unable to override them with a new version, because it's not published as NuGet package.
In order to solve this issue libraries add multiple targets, one for `netstandard2.0` and one `netcoreapp3.0`or higher (currently `3.1` since `3.0` no longer supported).
For example [Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/3.1.5) and other …
> Add netcoreapp3.1 as additional target for NuGet packages

- .pipelines/pipeline.user.windows.yml
- build.cmd
- build.ps1
- build/ChoosePowerShell.cmd
- build/InstallPowerShellCore.cmd
- pack.cmd
- pack.ps1
The change to target multiple frameworks resulted in a couple required changes to get build and pack working as expected.
* Use .NET Core 3.1 sdk container image
* Remove output path specification from build/pack command
* This causes the builds for each target framework to overwrite one another resulting in build errors and mispackaged binaries
* Updated build and pack to determine what PowerShell should be used
* .NET Core 3.1 container image comes with `pwsh` built-in
> Updated build pipeline to use .NET Core 3.1 sdk.

- README.md
GitHub drops punctuation in anchors, so link to `#MicrosoftTargeting` instead of `#Microsoft.Targeting`.
> Fix README links to Microsoft.Targeting section

- .pipelines/pipeline.user.yml
This pull request removes the unused reference to the configuration file for NuGet package sources.
> Remove package source with missing config file

- .pipelines/pipeline.user.yml
- NuGet.Config
This pull request adds NuGet.config with public feed as package source. This will allow packages to be fetched from this source even when no default path is configured.
> Add NuGet.config with public feed as package source

- examples/ConsoleApp/FeatureFilters/AccountIdFilter.cs
- examples/FeatureFlagDemo/BrowserFilter.cs
- examples/FeatureFlagDemo/HttpContextTargetingContextAccessor.cs
- examples/FeatureFlagDemo/SuperUserFilter.cs
- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/EmptySessionManager.cs
- src/Microsoft.FeatureManagement/IContextualFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/IFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureManager.cs
- src/Microsoft.FeatureManagement/ISessionManager.cs
- src/Microsoft.FeatureManagement/Targeting/ITargetingContextAccessor.cs
- tests/Tests.FeatureManagement/ContextualTestFilter.cs
- tests/Tests.FeatureManagement/InMemoryFeatureDefinitionProvider.cs
- tests/Tests.FeatureManagement/InvalidFeatureFilter.cs
- tests/Tests.FeatureManagement/OnDemandTargetingContextAccessor.cs
- tests/Tests.FeatureManagement/TestFilter.cs
* Added default value for cancellation token in interfaces to keep existing usage possible.
* Updated internal, unused cancellation token parameter names to be more appropriate.
With the addition of default values, the usage in 2.3.0 `_featureManager.IsEnabledAsync("Beta")` is preserved.
Based off of feedback in: #131
> Added default value for cancellation token in interfaces.

- src/Microsoft.FeatureManagement/FeatureManagementError.cs
- src/Microsoft.FeatureManagement/FeatureManagementOptions.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
> Added option to throw when attempting to evaluate a missing feature.

- src/Microsoft.FeatureManagement/FeatureManagerSnapshot.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/TestFilter.cs
The current implementation of IFeatureManagerSnapshot is not thread safe. This PR enhances the implementation to support concurrency.
Addresses #136
> Support concurrency in IFeatureManagerSnapshot

- src/Microsoft.FeatureManagement/FilterAliasAttribute.cs
Updated FilterAliasAttribute to use nameof(alias) when throwing an ArgumentNullException when the alias param is null or empty. Fix for issue #145.
> Updated FilterAliasAttribute to use nameof(alias) when throwing an ArgumentNullException when the alias param is null or empty.

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
> Updated version to 2.4.0.

- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
NextDouble() ∈ [0, 1). We use a strict inequality, so a 0% rollout value sporadically returns true as 0⩽0.
The fix is to use a non-strict inequality, <. The upper bound still works: 0.999... < 1.
We noticed this internally because feature flags were occasionally tripping even with 0% rollout. This appears to be the root cause.
> Fix PercentageFilter inequality bound

- README.md
- src/Microsoft.FeatureManagement.AspNetCore/FeatureGateAttribute.cs
- src/Microsoft.FeatureManagement.AspNetCore/FeatureGatedAsyncActionFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilterEvaluationContext.cs
- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilterSettings.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilterSettings.cs
- src/Microsoft.FeatureManagement/FeatureManagementOptions.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/IContextualFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureFilterMetadata.cs
- src/Microsoft.FeatureManagement/IFeatureManagementBuilder.cs
- src/Microsoft.FeatureManagement/IFeatureManagerSnapshot.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFeatureVariantAssigner.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFeatureVariantAssigner.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilterSettings.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
With the introduction of dynamic features, APIs were updated to distinguish between feature flags and dynamic features. As mentioned in #160 a few places were missed. This PR is a second pass to update spots that use "feature" where "feature flag" would be more appropriate.
> Updated missed "feature name" occurrences.

- src/Microsoft.FeatureManagement.AspNetCore/FeatureGateAttribute.cs
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
Update type/method summaries in FeatureGateAttribute.
Also, bumped package versions to 2.5.1 to get out a minor patch update with the change.
> Update type/method summaries in FeatureGateAttribute.

- README.md
Added documentation for FeatureGateAttribute usage on Razor pages.
> Added documentation for FeatureGateAttribute usage on Razor pages.

- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFeatureVariantAssigner.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingEvaluator.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/appsettings.json
This PR addresses an issue regarding audience matching precedence when assigning variants via targeting.
If the current user is targeted by name directly, the associated variant should always win. This has the highest precedence.
Next is a group match.
Finally, if none of the above matches occur, default rollout percentage should be used to select a matching variant. Otherwise, the default variant should be selected.
1. User
2. Group
3. Default Rollout
4. Default Variant
This is already detailed in the README, but the existing code did not behave this way.
> Fixed targeting assignment precedence.

- examples/FeatureFlagDemo/FeatureFlagDemo.csproj
- examples/FeatureFlagDemo/Program.cs
- examples/FeatureFlagDemo/Startup.cs
Update Azure App Configuration provider reference in example project to pull features using v2 schema.
> Update Azure App Configuration provider reference in example project to pull features using v2 schema.

- examples/ConsoleApp/ConsoleApp.csproj
- examples/CustomAssignmentConsoleApp/CustomAssignmentConsoleApp.csproj
- examples/FeatureFlagDemo/FeatureFlagDemo.csproj
- examples/TargetingConsoleApp/TargetingConsoleApp.csproj
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
Added .NET 6 as a target framework and removed .NET 5
.NET 5 is [out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).
> Added .NET 6 as a target framework and removed .NET 5

- src/Microsoft.FeatureManagement/ConfigurationDynamicFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/ConfigurationFeatureFlagDefinitionProvider.cs
- src/Microsoft.FeatureManagement/FeatureManagementError.cs
The v3 library adds a new schema for defining feature flags. The feature manager only reads feature flags using a single schema. If different feature flag sources such as multiple appsettings files, or a file and a feature flag provider are mixed and using different schemas it could cause feature flags to be hidden. 
In order to prevent a hard to troubleshoot situation where feature flags are not being found due to mixed schemas, this PR updates the feature management system to throw an exception if feature management schemas are mixed.
> Throw exception if feature management schemas are mixed to avoid unintentionally hiding feature flags.

- examples/TargetingConsoleApp/Identity/InMemoryUserRepository.cs
- examples/TargetingConsoleApp/appsettings.json
- src/Microsoft.FeatureManagement/Targeting/Audience.cs
- src/Microsoft.FeatureManagement/Targeting/BasicAudience.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/appsettings.json
In response to #123.
Audiences have historically been a list of users, groups, and rollout percentages. This change adds an additional field in Audience called **Exclusion**. This field holds a list of **Users** and **Groups**. These users and groups are evaluated before the rest of the Audience. If there is a match, the feature flag immediately returns false. 
If the targeting filter has sibling filters, they will still be evaluated after a false result.
`appsettings.json`
```json
{
"Name": "Targeting",
"Parameters": {
"Audience": {
"Users": [
"Jeff",
"Anne"
],
"Groups": [
{
"Name": "Management",
"RolloutPercentage": 100
},
{
"Name": "TeamMembers",
"RolloutPercentage": 45
}
],
"DefaultRolloutPercentage": 20,
"Exclusion": {
"Users": [
"Anne",
"Phil"
],
"Groups": [
"Contractor"
]
}
}
}
} …
```
> Adds exclude logic to Targeting and Audience, adds unit test, updates example to include exclude

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/FeatureDefinition.cs
- src/Microsoft.FeatureManagement/FeatureManagementError.cs
- src/Microsoft.FeatureManagement/FeatureManagementOptions.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/RequirementType.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/appsettings.json
In response to issue https://github.com/microsoft/FeatureManagement-Dotnet/issues/28.
And as a rewrite of PR https://github.com/microsoft/FeatureManagement-Dotnet/pull/192.
Filters on Feature Flags have always used "Any" logic. Our execution goes through each filter and when a single one returns "true", we end execution and return true. This PR adds "All" logic. For "All", the execution instead goes through each filter and when a single one returns "false", we end execution, returning false. Otherwise we return true.
In short- this PR: 
* Moves RequirementType from AspNetCore to the main .Net library.
* Defaults all unspecified Feature Flags to use "Any" logic
* Adds "All" logic to Feature Flag evaluation
```json
"AllFilterFeature": {
"RequirementType": "All",
"EnabledFor": [
{
"Name": …
```
> Adds Requirement Type All and Any to FeatureFlags

- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
Adds an edge case for the `1 / MaxInt` chance that a person is placed in exactly at 100%, which currently isn't handled by the existing `<`. Using `<=` would cause other percents to fall in multiple buckets, so the edge case only applies to 100, where there is no higher bucket.
> Add edge case for exact 100 bucket

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
With the release of v3 on the horizon, we can start adding misc. features that were waiting for a major version bump. 
This adjustment was requested in a couple issues
https://github.com/microsoft/FeatureManagement-Dotnet/issues/144
https://github.com/microsoft/FeatureManagement-Dotnet/issues/254
> Adjusts the configuration provider to no longer check top level for feature flags

- src/Microsoft.FeatureManagement/ContextualFeatureFilterEvaluator.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/FiltersWithDuplicatedAlias.cs
- tests/Tests.FeatureManagement/appsettings.json
Allow filters to share the same Alias. This PR will resolve #98.
One FeatureFilter and multiple ContextualFeatureFilters using different types of context can share the same Alias.
We plan to register built-in filter including percentage, time window and contextual targeting filters by default when AddFeatureManagement() is called.
However, the contextual targeting and targeting filter share the same alias "Microsoft.Targeting". Currently, feature management does not allow filters share the same alias. This PR will also un-block this.
> Allow different type of filters to share the same Alias

- src/Microsoft.FeatureManagement/FeatureManager.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
> Adjust to the behavior of the evaluation of contextual filter for unrecogniazed context type

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs
We have exposed FeatureManager to public, which make it possible to use Feature Management in other third-party DI container frameworks.
Currently, when our user wants to use Feature Management in other DI container (e.g. Autofac), they need to implement their own IFeatureDefinitionProvider and register it into DI container because the built-in ConfigurationDefinitionProvider is an internal class.
To provide more convenience for our users, I think it will be very helpful to expose ConfigurationFeatureDefinitionProvider to public so that users can use it directly.
> Expose ConfigurationFeatureDefinitionProvider to public

- src/Microsoft.FeatureManagement/FeatureManager.cs
Try to fix the bug introduced by 3.1.0.
The feature manager uses the shared memory cache and it doesn't specify the entry size. This will cause error if the shared memory cache has a size limit. #325
> Add size for cache entry

- src/Microsoft.FeatureManagement/FeatureManagementBuilderExtensions.cs
Adjust the order of methods in FeatureManagementBuilder.Extension.cs
> Move public method to the front of private method

- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/ApplicationInsightsTelemetryExtensions.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/TelemetryClientExtensions.cs
Adds TargetingContext extension method for:
1. TrackEvent
2. TrackMetric
There are other track calls, but those calls are not a part of the happy path. `TargetingId` is only helpful in the happy path. Does not add extensions for:
1. TrackTrace
2. TrackException
3. TrackDependency
4. TrackAvailability
> Adds extension methods for TrackEvent and TrackMetric

- src/Microsoft.FeatureManagement/FeatureManager.cs
I found that the cache key for feature filter settings is different in preview branch. The cache key will have a prefix of "FeatureManagement". I think this is better.
https://github.com/microsoft/FeatureManagement-Dotnet/blob/preview/src/Microsoft.FeatureManagement/FeatureManager.cs#L666
> Add feature management prefix for cache key

- src/Microsoft.FeatureManagement/FeatureManager.cs
Went through every Task in our library and tried to switch them to ValueTask without affecting the public interface. These are the only ones that could change.
> Adjusts FeatureManager private methods from Task to ValueTask

- Microsoft.FeatureManagement.sln
- src/Microsoft.FeatureManagement.AspNetCore/TargetingHttpContextMiddleware.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore/TargetingTelemetryInitializer.cs
This PR introduces the idea of `TargetingId`. This is separate from UserId, although commonly they may be the same value. `TargetingId` is used to reflect which id was actually used for Feature Evaluation. This `TargetingId` can be tagged on events & metrics to connect events to evaluation events, emitted from a telemetry publisher. 
This was added in a new project, `Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore`. `TargetingTelemetryInitializer` is only relevant for Application Insights telemetry in ASP.NET Core.
This was added to `Microsoft.FeatureManagement.AspNetCore`. `TargetingHttpContextMiddleware` simply adds the TargetingId to HttpContext to enable Synchronous code to quickly access it. This is helpful for things like Telemetry Initializers. 
The example …
> Adds targeting middleware and targeting initializer

- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs
According to https://github.com/MicrosoftDocs/azure-docs-pr/pull/264613#discussion_r1475561565
This change will simplify the non-DI usage of feature management a little bit.
> Add a constructor without FeatureManagementOption parameter for FeatureManager

- schemas/FeatureManagement.Dotnet.v1.0.0.schema.json
- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- tests/Tests.FeatureManagement/appsettings.json
Small follow up to https://github.com/microsoft/FeatureManagement-Dotnet/pull/362
> Updates test/comment schema and adjusts schema title

- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilter.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilter.cs
> Update constructors of built-in feature filters

- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/ISessionManager.cs
- src/Microsoft.FeatureManagement/IVariantFeatureManager.cs
According to #376  
BTW, all AppConfig SDK public APIs made the CancellationToken optional: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs
This PR makes cancellation token optional for async methods of IVariantFeatureManager and adds cancellation token to async methods of ISessionManager
> Optional Cancellation Token

- tests/Tests.FeatureManagement.AspNetCore/FeatureManagementAspNetCore.cs
- tests/Tests.FeatureManagement.AspNetCore/Features.cs
> Update the way to reference feature flag in ASP.NET test suite

- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingEvaluator.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilter.cs
Currently, the validation of TargetingFilterSettings will happened on every request, which is unnecessary. 
Usually, filter settings will be prebound and be cached in the feature manager. It will be passed to the feature filter as part of `FeatureFilterEvaluationContext`. The `BindParameters` method will only be called once and there is only one filter settings. 
So, I propose to move the settings validation to `TargetingFilter.BindParameters` from `TargetingEvaluator.IsTargeted`.
> Avoid redundant validation for cached TargetingFilterSettings

- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/TelemetryClientExtensions.cs
Addresses https://github.com/microsoft/FeatureManagement-Dotnet/issues/391
Developers using our Application Insights extension methods will have the methods available from their existing `using Microsoft.ApplicationInsights;`.
Developers no longer require the `using Microsoft.FeatureManagement.Telemetry.ApplicationInsights;`.
> Adjusts ApplicationInsights extension methods namespace

- examples/EvaluationDataToApplicationInsights/Program.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore/TargetingTelemetryInitializer.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/ApplicationInsightsTelemetryPublisher.cs
Addresses https://github.com/microsoft/FeatureManagement-Dotnet/issues/392
Developers using any of our offered telemetry publishers will use `using Microsoft.FeatureManagement.Telemetry;` and developers using any of our offered telemetry initializers will use `using Microsoft.FeatureManagement.Telemetry.AspNetCore;`. 
We will no longer have service specific namespaces like `using ~.ApplicationInsights.~;` except for extension methods.
> Adjusts namespace to simply ~.Telemetry

- src/Microsoft.FeatureManagement/Targeting/TargetingEvaluator.cs
> Ensure the consistency of targeting evaluation across CPU architectures.

- src/Microsoft.FeatureManagement/FeatureManager.cs
Adjusts warning logs identified in https://github.com/microsoft/FeatureManagement-Dotnet/issues/425
Developers will no longer see this warning when using flags that don't require TargetingContext.
```
No instance of ITargetingContextAccessor is available for variant assignment.
```
This warning will only show if they have variants defined and we've reached the place in code where allocation would happen.
> Warning log missing targeting context accessor

- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilter.cs
Bug fix.
We have null check for `FeatureFilterEvaluationContext` in `EvaluateAsync` method of ContextualTargeting and Targeting filters.
We missed that in TimeWindowFilter and PercentageFilter. This could cause potential NPE, since we access context.Settings without check whether context is null.
> Add context null check for built-in filters

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
A developer had an issue. After refresh they were getting:
> Object reference not set to an instance of an object
> at Microsoft.FeatureManagement.FeatureManager.\<GetFeatureNamesAsync>d__10.MoveNext()
After trying to recreate the issue, I found one way. The steps are as follows:
1. Call `FeatureManager.GetFeatureNamesAsync()`.
2. Iterate the first item in the AsyncEnumerable. ( This means, `ConfigurationFeatureDefinitionProvider.GetAllFeatureDefinitionsAsync` will iterate once, meaning it will grab a list of all `IConfigurationSections` defined within FeatureManagement, but only iterate the first one )
3. Remove a flag from the Configuration
4. Refresh configuration
5. Call `IsEnabledAsync("RemovedFlag")` or iterate through a full `GetFeatureNamesAsync`. This fills the cache with "null". …
> Moves cache busting and handles null

- README.md
- src/Microsoft.FeatureManagement.AspNetCore/FeatureGateAttribute.cs
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/FeatureFilters/ISystemClock.cs
- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/Recurrence.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceEvaluator.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrencePattern.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrencePatternType.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceRange.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceRangeType.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceValidator.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilterSettings.cs
- src/Microsoft.FeatureManagement/FeatureManagementBuilder.cs
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilter.cs
- tests/Tests.FeatureManagement.AspNetCore/FeatureManagementAspNetCore.cs
- tests/Tests.FeatureManagement.AspNetCore/Features.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/OnDemandClock.cs
- tests/Tests.FeatureManagement/RecurrenceEvaluation.cs
- tests/Tests.FeatureManagement/appsettings.json
Changes include:
1. TimeWindow recurring filter https://github.com/microsoft/FeatureManagement-Dotnet/pull/266
2. Bug fix for async enumerable on feature flag names https://github.com/microsoft/FeatureManagement-Dotnet/pull/438
3. Makes loggerfactory optional for built-in filters https://github.com/microsoft/FeatureManagement-Dotnet/pull/386
> Merge main into release v3

- src/Microsoft.FeatureManagement/FeatureManagementBuilder.cs
Bug fix #447 
``` C#
services.AddFeatureManagement()
.AddFeatureFilter<TimeWindowFilter>();
```
The call of `AddFeatureFilter` on the `IFeatureManagementBuilder` returned by the `AddFeatureManagement` call will no longer register `TimeWindowFilter` repeatedly.
This PR added a check in the `AddFeatureFilter<T>()` method of the `FeatureManagementBuilder` class, if the `T` is `TimeWindowFilter`, the method will do nothing. 
All built-in feature filters are registered during the `AddFeatureManagement` call, the `TimeWindowFilter` is registered through the overload `AddFeatureFilter<T>(Func implemenetationFactory)
The `FeatureManagementBuilder` is internal and only be created in the `AddFeatureManagment` call, this ensures that AddFeatureFilter<T>()` will only be called after calling …
> Bug Fix - Avoid duplicated registration of TimeWindowFilter through AddFeatureFilter method

- README.md
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
#447 
https://github.com/Azure/azure-sdk-for-java/pull/40093#discussion_r1596958545
Also include a small change to remove an unused reference in this PR
Update README
Remove an unused reference
> Update README to emphasize built-in filters are add automatically and adjust wording

- README.md
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/FeatureManagementBuilder.cs
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
> Merge main to release v3

- examples/EvaluationDataToApplicationInsights/Program.cs
- examples/VariantServiceDemo/Program.cs
- src/Microsoft.FeatureManagement.AspNetCore/AspNetCoreFeatureManagementBuilderExtensions.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/FeatureManagementBuilderExtensions.cs
Preview now with app insights telemetry looks like this:
```csharp
// Add App Insights
builder.Services.AddApplicationInsightsTelemetry(); // Shouldn't be done by us
builder.Services.AddHttpContextAccessor();
// Add FeatureManagement's TargetingTelemetryInitializer
builder.Services.AddSingleton<ITelemetryInitializer, TargetingTelemetryInitializer>();
// Add FeatureManagement
builder.Services.AddFeatureManagement()
.WithTargeting() // Uses DefaultHttpTargetingAccessor, requires HttpContextAccessor
.AddApplicationInsightsTelemetryPublisher();
var app = builder.Build();
//...
app.UseMiddleware<TargetingHttpContextMiddleware>();
```
Making a few opinionated changes- we can make it:
```csharp
// Add App Insights
builder.Services.AddApplicationInsightsTelemetry(); // Shouldn't be done by us …
```
> Adjusts builder extension methods to be friendlier

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/MicrosoftFeatureManagementFields.cs
- src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs
- src/Microsoft.FeatureManagement/VariantDefinition.cs
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/appsettings.json
#489 
`configuration_reference` is not longer supported.
> Remove configuration reference from variant feature flag

- examples/VariantServiceDemo/Pages/Privacy.cshtml.cs
- src/Microsoft.FeatureManagement.AspNetCore/AspNetCoreFeatureManagementBuilderExtensions.cs
- src/Microsoft.FeatureManagement.AspNetCore/TargetingHttpContextMiddleware.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/FeatureManagementBuilderExtensions.cs
- src/Microsoft.FeatureManagement/FeatureManagementBuilderExtensions.cs
- src/Microsoft.FeatureManagement/FeatureManagementOptions.cs
- src/Microsoft.FeatureManagement/FeatureStatus.cs
- src/Microsoft.FeatureManagement/StatusOverride.cs
Small changes to cleanup preview
> Preview cleanup

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- tests/Tests.FeatureManagement/DotnetFeatureManagementSchema.json
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/appsettings.json
Updates the flag provider to handle duplicate flags by using the last flag instead of the first. 
* For the [Microsoft Feature Flag Schema](https://github.com/microsoft/FeatureManagement/blob/main/Schema/FeatureManagement.v2.0.0.schema.json) - When there are duplicate feature flag ids- the last flag will be used. This allows multiple flag providers or multiple sources to load flags in a consistent way across languages. 
* This also aligns with the existing functionality in stable. 
* This change only affects the built-in `ConfigurationFeatureDefinitionProvider`, custom providers are still in charge of their ordering.
> Last one wins flag providers

- src/Microsoft.FeatureManagement.AspNetCore/TagHelpers/FeatureTagHelper.cs
- src/Microsoft.FeatureManagement/FeatureManagerSnapshot.cs
- src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs
- tests/Tests.FeatureManagement.AspNetCore/FeatureManagementAspNetCore.cs
- tests/Tests.FeatureManagement.AspNetCore/Tests.FeatureManagement.AspNetCore.csproj
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
* Resolves breaking change with `IFeatureManagerSnapshot` brought up by https://github.com/microsoft/FeatureManagement-Dotnet/issues/117#issuecomment-2369011536
* More unit tests to catch similar issues in the future. 
* `IFeatureManagerSnapshot` and `FeatureTagHelper` now require both an `IFeatureManager` and an `IVariantFeatureManager`. For the common case, these will refer to the same instance. By separating them, we preserve backwards compatability for custom `IFeatureManager` implementations.
> Resolves snapshot breaking change and adjusts feature tag helper as well

- examples/RazorPages/Pages/Index.cshtml.cs
- src/Microsoft.FeatureManagement.AspNetCore/FeatureGateAttribute.cs
- tests/Tests.FeatureManagement.AspNetCore/FeatureManagementAspNetCore.cs
- tests/Tests.FeatureManagement.AspNetCore/Pages/RazorTestAllNegate.cshtml
- tests/Tests.FeatureManagement.AspNetCore/Pages/RazorTestAllNegate.cshtml.cs
- tests/Tests.FeatureManagement.AspNetCore/Pages/RazorTestAnyNegate.cshtml
- tests/Tests.FeatureManagement.AspNetCore/Pages/RazorTestAnyNegate.cshtml.cs
- tests/Tests.FeatureManagement.AspNetCore/TestController.cs
#202 
Add `Negate` property to `FeatureGateAttribute` and add more constructors for it to allow the following usage:
``` C#
[FeatureGate(requirementType: RequirementType.Any, negate: false, ["Home"])]
```
> Negate FeatureGateAttribute

- build/install-dotnet.ps1
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- tests/Tests.FeatureManagement.AspNetCore/Tests.FeatureManagement.AspNetCore.csproj
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
.NET 6 has been out of support since Nov, 2024
#517 #524
> Drop .net 6

- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/ApplicationInsightsEventPublisher.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
Currently, we put `VariantAssignementReason` enum in the activity tags. [ref](https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/src/Microsoft.FeatureManagement/FeatureManager.cs#L387)
When putting it into app insights telemetry, we call `ToString` on Enum type, this is not a good practice. Because, code refactoring may cause the value in telemetry changed.
We also call `ToString` on boolean, which will produce "True" instead of "true". Since all of our released packages have the same behavior, we should keep it. But it should be hard-coded. Like JS FM does [ref](https://github.com/microsoft/FeatureManagement-JavaScript/blob/main/src/feature-management/src/telemetry/featureEvaluationEvent.ts#L22) and [ref](https://github.com/microsoft/FeatureManagement-JavaScript/blob/main/src …
> Avoid using boolean.ToString and enum.ToString

- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceEvaluator.cs
- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceValidator.cs
- tests/Tests.FeatureManagement/RecurrenceEvaluation.cs
The validation of recurrence configuration has been decoupled from recurrence evaluation. I forgot to update the related testcase. Also, update the implementation to make it more readable, not a bug fix.
related PR: #266 
-changes that are visible to developers using this library-
> Small fix for recurring time window testcase

- examples/ConsoleApp/Program.cs
- examples/TargetingConsoleApp/Program.cs
Showcase the non-DI usage of feature management
Update the console app examples
> Do not use DI for console app example

- src/Microsoft.FeatureManagement/MicrosoftFeatureManagementFields.cs
Broken link hurts readability and discoverability
- Replaced a broken link to JSON schema V1 with working link to JSON schema v2
- Used the XML doc format `/// <summary]`
- Removed empty like comments `//`
> Fixed broken link to JSON schema in MicrosoftFeatureManagementFields.cs

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- src/Microsoft.FeatureManagement/Telemetry/FeatureEvaluationTelemetry.cs
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/appsettings.json
> Merge preview to main

- src/Microsoft.FeatureManagement.AspNetCore/TargetingHttpContextMiddleware.cs
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/TargetingTelemetryInitializer.cs
There are redundant `TargetingId` dimension in our telemetry.
The `TargetingHttpContextMiddleware` adds `Microsoft.FeatureManagement.TargetingId` to http request activity baggage.
The baggage will be inherited by child activities and App Insights SDK will add it to the event's custom dimension.
[ref](https://learn.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#applicationinsights-operations-vs-systemdiagnosticsactivity)
> Rename TargetingId baggage

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
Fixed a bug introduced in 4.2.0: #546
> Bug fix - Respect root configuration fallback
