- .pipelines/pipeline.user.windows.yml
- build.cmd
- build.ps1
- build/InstallPowerShellCore.cmd
- build/NugetProperties.props
- pack.cmd
Recent changes in build infrastructure have mandated some changes in the build. This PR fixes these issues.
> Fixed the build and package process.

- README.md
Fixed readme example and naming.
> Fixed readme example and naming.

- build/NugetProperties.props
This update will enable the production of
Microsoft.FeatureManagement 2.0.0
Microsoft.FeatureManagement.AspNetCore 2.0.0
> Updated build properties to produce stable package version.

- README.md
- Mark them as a specific language so they get syntax highlighting
- Unify spacing to 4 spaces
- Use … consistently
This is entirely containing only stylistic changes and no changes to the samples themselves.
Click the following button on the _Files changed_ tab to make this easier to see the changes.
> Clean up code sample blocks

- build/NugetProperties.props
The new version introduces new APIs thus requiring a minor version change.
> Update version 2.0.0 -> 2.1.0

- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Features.cs
- tests/Tests.FeatureManagement/OnDemandTargetingContextAccessor.cs
- tests/Tests.FeatureManagement/appsettings.json
Tests were omitted from the targeting PR. This PR adds tests to ensure targeting is functional and not broken in the future.
> Added test for targeting.

- build/NugetProperties.props
This new release will include the following changes:
* Added NetCoreApp3.1 as a targeted framework #77 
* Added IFeatureDefinitionProvider APIs to enable external feature providers. #79
> Updated version to 2.2.0-preview for release

- README.md
Update custom feature provider readme section to be more to the point for what their purpose is.
> Update readme to improve the custom feature provider section.

- build/NugetProperties.props
Remove preview for 2.2.0 release.
> Remove preview for 2.2.0 release.

- .pipelines/pipeline.user.windows.yml
- test.cmd
This pull request enables unit tests as a part of automated builds for PR validation and continuous integration.
> Enable unit tests in automated builds

- .pipelines/pipeline.user.windows.yml
- examples/ConsoleApp/ConsoleApp.csproj
- examples/FeatureFlagDemo/FeatureFlagDemo.csproj
- examples/TargetingConsoleApp/TargetingConsoleApp.csproj
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
Add net5.0 target framework.
* Add target framework
* Update build image to have 5.0 sdk
* Updated tests to run all supported target frameworks.
> Add net5.0 target framework.

- build/NugetProperties.props
- build/Versioning.props
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
* Updated Microsoft.FeatureManagement to 2.3.0 for release.
* Release adds .net 5 as a target.
* Updated build to use separate versions for different projects.
> Updated Microsoft.FeatureManagement to 2.3.0 for release.

- examples/ConsoleApp/FeatureFilters/AccountIdFilter.cs
- examples/FeatureFlagDemo/BrowserFilter.cs
- examples/FeatureFlagDemo/HttpContextTargetingContextAccessor.cs
- examples/FeatureFlagDemo/SuperUserFilter.cs
- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/EmptySessionManager.cs
- src/Microsoft.FeatureManagement/IContextualFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/IFeatureFilter.cs
- src/Microsoft.FeatureManagement/IFeatureManager.cs
- src/Microsoft.FeatureManagement/ISessionManager.cs
- src/Microsoft.FeatureManagement/Targeting/ITargetingContextAccessor.cs
- tests/Tests.FeatureManagement/ContextualTestFilter.cs
- tests/Tests.FeatureManagement/InMemoryFeatureDefinitionProvider.cs
- tests/Tests.FeatureManagement/InvalidFeatureFilter.cs
- tests/Tests.FeatureManagement/OnDemandTargetingContextAccessor.cs
- tests/Tests.FeatureManagement/TestFilter.cs
Reverts microsoft/FeatureManagement-Dotnet#133
> Revert "Added default value for cancellation token in interfaces."

- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/FeatureDefinition.cs
- src/Microsoft.FeatureManagement/FeatureManagementError.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- tests/Tests.FeatureManagement/FeatureManagement.cs
- tests/Tests.FeatureManagement/appsettings.json
Reverts microsoft/FeatureManagement-Dotnet#143
> Revert "Add the capability to prevent features with feature filters from being evaluated."

- src/Microsoft.FeatureManagement/DynamicFeatureManager.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingEvaluator.cs
This PR adds missing null argument validation on feature names in feature manager.
> Added null check validation for feature name.

- README.md
> docs: add nuget badge for readme

- README.md
The number stuck out, updated to use word for sentence.
> Minor readme update.

- examples/ConsoleApp/Program.cs
- examples/FeatureFlagDemo/FeatureNotEnabledDisabledHandler.cs
Fixed the bug: FeatureNotEnabled page cannot be displayed.
The bug is caused by this PR: https://github.com/microsoft/FeatureManagement-Dotnet/pull/277/files#diff-a2a57d67b05ce1c160fe09f0c2ef888e6da6073a786fa61d89c3d572fd8ecc95
> Fix the bug in feature flag demo example

- Microsoft.FeatureManagement.sln
The App Insights telemetry project got added to the solution twice in the preview branch.
> Fix project added twice.

- README.md
This PR updates the README to detail the libraries telemetry capabilities as well as instructions on how to enable telemetry.
> Add readme section detailing telemetry capabilities.

- README.md
- examples/ConsoleApp/Program.cs
- examples/FeatureFlagDemo/FeatureNotEnabledDisabledHandler.cs
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/FeatureManager.cs
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
> Merge main to release/v3

- tests/Tests.FeatureManagement/appsettings.json
Sorry I didn't notice that I messed up the tab size of the appsettings.json in the Test.FeatureManagement project.
> Adjust tab size of json file

- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilter.cs
Maintain a consistent code style.
https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/src/Microsoft.FeatureManagement/FeatureManager.cs#L219
https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs#L367
> Remove redundant if check for logger

- README.md
- src/Microsoft.FeatureManagement.AspNetCore/FeatureGateAttribute.cs
- src/Microsoft.FeatureManagement/FeatureFilters/PercentageFilter.cs
- src/Microsoft.FeatureManagement/FeatureFilters/TimeWindowFilter.cs
- src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs
- src/Microsoft.FeatureManagement/Targeting/TargetingFilter.cs
- tests/Tests.FeatureManagement.AspNetCore/FeatureManagementAspNetCore.cs
- tests/Tests.FeatureManagement.AspNetCore/Features.cs
I made a mistake to use the "Squash and merge" last time when I merged main to preview, that's the reason why there are so many commits here.
> Merge main to preview

- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
> Update target framework for telemetry packages

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
Prepare for new preview release.
Microsoft.FeatureManagement packages: 4.0.0-preview2 -> 4.0.0-preview3
> Preview version bump

- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore.csproj
#390 
`Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore` package will include `Microsoft.FeatureManagement.Telemetry.ApplicationInsights`
> Add dependency for telemetry aspnetcore package

- src/Microsoft.FeatureManagement/FeatureFilters/Recurrence/RecurrenceValidator.cs
Simplify the code. No logic change.
> Simplify IsDurationCompliantWithDaysOfWeek method

- src/Microsoft.FeatureManagement/Targeting/TargetingEvaluator.cs
> 4.0.0-preview Bug fix: NullReferenceException when TargetingContext.UserId is null

- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/ApplicationInsightsEventPublisher.cs
- src/Microsoft.FeatureManagement/FeatureManager.cs
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
From https://github.com/microsoft/FeatureManagement-Dotnet/pull/455#discussion_r1646673545
> Rossgrambo Activity Event Naming

- Directory.Build.props
- examples/BlazorServerApp/BlazorServerApp.csproj
- examples/ConsoleApp/ConsoleApp.csproj
- examples/FeatureFlagDemo/FeatureFlagDemo.csproj
- examples/RazorPages/RazorPages.csproj
- examples/TargetingConsoleApp/TargetingConsoleApp.csproj
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- tests/Tests.FeatureManagement.AspNetCore/Tests.FeatureManagement.AspNetCore.csproj
- tests/Tests.FeatureManagement/Tests.FeatureManagement.csproj
https://github.com/Azure/AppConfiguration-DotnetProvider/pull/571#discussion_r1680535331
> Add directory props

- README.md
- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
Prep for release.
* Next deploy will no longer be preview.
* Link in readme will point to stable.
> Removes preview

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
> Version bump 4.1.0

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
> Version bump 4.2.0

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
> Version bump 4.2.1

- src/Microsoft.FeatureManagement.AspNetCore/Microsoft.FeatureManagement.AspNetCore.csproj
- src/Microsoft.FeatureManagement.Telemetry.ApplicationInsights/Microsoft.FeatureManagement.Telemetry.ApplicationInsights.csproj
- src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs
- src/Microsoft.FeatureManagement/Microsoft.FeatureManagement.csproj
- tests/Tests.FeatureManagement/FeatureManagementTest.cs
> Merge main to release/v4
